# Generated by Django 4.0.2 on 2022-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('head0', models.CharField(default='', max_length=500)),
                ('para0', models.CharField(default='', max_length=50000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('para1', models.CharField(default='', max_length=50000)),
                ('head3', models.CharField(default='', max_length=500)),
                ('para3', models.CharField(default='', max_length=50000)),
                ('head4', models.CharField(default='', max_length=500)),
                ('para4', models.CharField(default='', max_length=50000)),
                ('Pub_date', models.DateField()),
                ('Thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
